/* ================= SERVICES ================= */
export const services = [
  {
    id: 1,
    name: "Web Development",
    slug: "web-development",
    description: "Modern, responsive websites & web apps.",
    icon: "Code",
  },
  {
    id: 2,
    name: "UI/UX Design",
    slug: "ui-ux-design",
    description: "Clean, intuitive, and user-focused design.",
    icon: "Layout",
  },
  {
    id: 3,
    name: "API / Backend",
    slug: "backend-api",
    description: "Scalable & secure server-side solutions.",
    icon: "Database",
  },
  {
    id: 4,
    name: "Company Profile",
    slug: "company-profile",
    description: "Professional company profile websites.",
    icon: "FileText",
  },
  {
    id: 5,
    name: "Mobile Apps",
    slug: "mobile-apps",
    description: "iOS & Android application development.",
    icon: "Smartphone",
  },
];

/* ================= PORTFOLIOS ================= */
export const portfolios = [
  {
    id: 1,
    name: "E-Commerce Platform",
    slug: "ecommerce-platform",
    category: "Web App",
    description: "Full-featured marketplace with admin dashboard.",
    client: "Retail Company",
    year: 2025,
    techStack: ["Next.js", "Node.js", "PostgreSQL"],
    image: "https://picsum.photos/600/400?random=1",
    thumbnail: "/images/portfolio1-thumb.png",
    liveUrl: "https://example.com",
    repoUrl: "",
    featured: true,
    status: "Completed",
  },

  {
    id: 2,
    name: "Healthcare Website",
    slug: "healthcare-website",
    category: "Company Profile",
    description: "Modern website for clinic and patient services.",
    client: "Medical Clinic",
    year: 2025,
    techStack: ["React", "Tailwind", "Firebase"],
    image: "https://picsum.photos/600/400?random=2",
    thumbnail: "/images/portfolio2-thumb.png",
    liveUrl: "",
    repoUrl: "",
    featured: true,
    status: "Completed",
  },

  {
    id: 3,
    name: "Fintech Dashboard",
    slug: "fintech-dashboard",
    category: "Dashboard",
    description: "Analytics dashboard for financial data tracking.",
    client: "Finance Startup",
    year: 2025,
    techStack: ["React", "Express", "PostgreSQL"],
    image: "https://picsum.photos/600/400?random=3",
    thumbnail: "/images/portfolio3-thumb.png",
    liveUrl: "",
    repoUrl: "",
    featured: true,
    status: "Completed",
  },

  {
    id: 4,
    name: "Learning Management System",
    slug: "lms-platform",
    category: "Web App",
    description: "Online learning platform with course management.",
    client: "Education Company",
    year: 2025,
    techStack: ["Next.js", "Firebase", "Redux"],
    image: "https://picsum.photos/600/400?random=4",
    thumbnail: "/images/portfolio4-thumb.png",
    liveUrl: "",
    repoUrl: "",
    featured: false,
    status: "Completed",
  },

  {
    id: 5,
    name: "Restaurant Ordering App",
    slug: "restaurant-app",
    category: "Mobile App",
    description: "Online food ordering mobile application.",
    client: "Restaurant Chain",
    year: 2024,
    techStack: ["React Native", "Node.js"],
    image: "https://picsum.photos/600/400?random=5",
    thumbnail: "/images/portfolio5-thumb.png",
    liveUrl: "",
    repoUrl: "",
    featured: false,
    status: "Completed",
  },

  {
    id: 6,
    name: "Corporate Website",
    slug: "corporate-website",
    category: "Company Profile",
    description: "Professional website for corporate branding.",
    client: "Corporate Client",
    year: 2024,
    techStack: ["Next.js", "Tailwind"],
    image: "https://picsum.photos/600/400?random=6",
    thumbnail: "/images/portfolio6-thumb.png",
    liveUrl: "",
    repoUrl: "",
    featured: false,
    status: "Completed",
  },

  {
    id: 7,
    name: "Booking System",
    slug: "booking-system",
    category: "Web App",
    description: "Online booking system with real-time availability.",
    client: "Service Business",
    year: 2025,
    techStack: ["React", "MongoDB"],
    image: "https://picsum.photos/600/400?random=7",
    thumbnail: "/images/portfolio7-thumb.png",
    liveUrl: "",
    repoUrl: "",
    featured: false,
    status: "Completed",
  },

  {
    id: 8,
    name: "Admin CMS Dashboard",
    slug: "cms-dashboard",
    category: "Dashboard",
    description: "Custom CMS dashboard for content management.",
    client: "Media Company",
    year: 2025,
    techStack: ["Next.js", "Express", "MySQL"],
    image: "https://picsum.photos/600/400?random=8",
    thumbnail: "/images/portfolio8-thumb.png",
    liveUrl: "",
    repoUrl: "",
    featured: false,
    status: "Completed",
  },
];

/* ================= ARTICLES ================= */
export const articles = [
  {
    id: 1,
    title: "Why Every Business Needs a Website",
    slug: "why-business-needs-website",
    excerpt: "Discover why having a website is essential today.",
    image: "https://picsum.photos/600/400?random=1",
    createdAt: "2025-01-01",
  },
];

/* ================= PROCESS ================= */
export const process = [
  {
    id: 1,
    step: "01",
    title: "Consult",
    description: "We discuss your goals and requirements.",
    icon: "MessageCircle",
  },
  {
    id: 2,
    step: "02",
    title: "Design",
    description: "UI/UX design and wireframing process.",
    icon: "Lightbulb",
  },
  {
    id: 3,
    step: "03",
    title: "Develop",
    description: "Building with clean and scalable code.",
    icon: "Code",
  },
  {
    id: 4,
    step: "04",
    title: "Launch",
    description: "Testing, deployment, and go live.",
    icon: "Rocket",
  },
];

/* ================= CONTACT ================= */
export const contacts = [
  {
    id: 1,
    phone: "082310001570",
    website: "http://www.sadinotech.com",
    instagram: "sadino.tech",
    email: "hello@sadinotech.com",
    location: "Indonesia",
    notes: "",
  },
];
